### ISSUE TITLE
antd-mobile 5.12.7 版本 CSS通配符报错：./pages/index/index.wxss  error at token "*" 

### ISSUE THREAD

**Issue by x011223** [NervJS/taro-antd-mobile#7]
### 开发环境

MacOS - 12.3.1
调试基础库 - 2.17.0

### 报错信息

![image](https://user-images.githubusercontent.com/31724313/169931910-557abda5-658f-4953-8e79-fae2e07fe846.png)

### packages
```json
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/cli": "3.4.6",
    "@tarojs/components": "3.4.6",
    "@tarojs/plugin-framework-react": "3.4.6",
    "@tarojs/react": "3.4.6",
    "@tarojs/runtime": "3.4.6",
    "@tarojs/taro": "3.4.6",
    "antd-mobile": "^5.12.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "taro-hooks": "latest"
  },
```

**Comment by x011223** [comment]
这个可能需要用babel plugin去处理了。

**Comment by Chen-jj** [comment]
Taro 有用一个 postcss 插件去 remove 带有 `*` 的样式，可以调试看看有没有生效 https://github.com/NervJS/taro/blob/5e57252a81409389b85b8786db5d3d9d92246161/packages/postcss-html-transform/src/index.ts#L12-L13

**Comment by x011223** [comment]
> Taro 有用一个 postcss 插件去 remove 带有 `*` 的样式，可以调试看看有没有生效 https://github.com/NervJS/taro/blob/5e57252a81409389b85b8786db5d3d9d92246161/packages/postcss-html-transform/src/index.ts#L12-L13

感谢，`postcss-html-transform` 可以处理这个报错，但是 `scheduler` 这个库 又报错了，应该是 `antd-mobile` 引用了这个, 问题比较多，可能会放弃。
